name: Deploy on server

on: [push]

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: files upload
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: brs1new.internetway.net
          ftp_username: brs
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          dist_target_dir: /srv/www/brs/brsbrokers.com/www/htdocs/website_test/
          delete: "true"
          ftps: initial-prot
